// fixtures/languages/test.vue
<template>
  <!-- This HTML comment should be removed -->
  <div class="app">
    <p>Hello Vue!</p>
    <!-- TODO: add dynamic content -->
  </div>
</template>

<script>
// This line comment should be removed
/* This block comment should be removed */
export default {
  name: "App",
  data() {
    const url = "http://example.com#anchor";
    const note = "// not a comment";
    // eslint-disable-next-line no-unused-vars
    return { url, note };
  },
};
</script>

<style scoped>
/* This CSS comment should be removed */
.app {
  color: red;
}
</style>

// fixtures/languages/test.svelte
<!-- This HTML comment should be removed -->
<script>
  // This line comment should be removed
  let name = "world";
  let msg = "<!-- not a comment -->";
  // TODO: add reactivity
  // eslint-disable-next-line no-unused-vars
  let unused = 42;
</script>

<!-- TODO: improve layout -->
<main>
  <h1>Hello {name}!</h1>
  <p>Content with <!-- inline --> markup</p>
</main>

<style>
  /* This CSS comment should be removed */
  h1 {
    color: purple;
  }
</style>
